# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.
#
# If you need help with YAML syntax, here are some quick references for you:
# https://learn-the-web.algonquindesign.ca/topics/markdown-yaml-cheat-sheet/#yaml
# https://learnxinyminutes.com/docs/yaml/
#
# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.

title: "King's Dominion"
name: "Anmol Shah"
email: shahkanmol@example.com
description: >- # this means to ignore newlines until "baseurl:"
  The website for a guy who's into a lot of things. If you want to talk about life or something, I'm always down.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://sxkuroki/sxkuroki.github.io" # the base hostname & protocol for your site, e.g. http://example.com
github_username:  sxkuroki
repository: "sxkuroki/sxkuroki.github.io"
# Build settings
#theme: "minimal-mistakes-jekyll"
remote_theme: "mmistakes/minimal-mistakes"
minimal_mistakes_skin: "neon"
plugins:
  - jekyll-feed
  - jekyll-include-cache

title_seperator: "|"

defaults:
  #_posts
  - scope:
      path: ""
      type: posts
    values:
      show_date: true
      read_time: true

author:
  name: "Anmol Shah"
  avatar: "/assets/images/bio-photo.jpg"
  bio: "I'm just a guy into comic books, cryptography, number theory, anime, and people things. Hit me up if you want to talk about **anything**"
  location: "Undisclosed"
  links: 
    - label: "King's Dominion"
      icon: "fas fa-fw fa-link"
      url: "https://sxkuroki.github.io"
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/sxkuroki"

lunr:
  search_within_pages: true










# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
